a = input('Digite algo: ')
print('Está só em maiúsculo: ' , a.isupper())
print('Está só em minúsculo: ' , a.islower())
print('É um dígito: ' , a.isdigit())
print('É um indentificador: ' , a.isidentifier())
print('É imprimível: ' , a.isprintable())
print('É alfanumérico: ', a.isalnum())
print('Só tem espaços: ', a.isspace())
print('Está capitalizada: ' , a.istitle())
print('É um número decimal: ' , a.isdecimal())
# não sei o próximo .Valdir
print('' , a.isascii())
print('É somente alfabético: ' , a.isalpha())
print('É apenas numérico: ' , a.isnumeric())