n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número: '))
soma = n1 + n2
print('A soma entre {} e {} é de: {}'.format(n1 ,n2 ,soma))
n3 = input('Digite algo outra vez: ')
print(n3.isupper())
print(n3.islower())
print(n3.isdigit())
print(n3.isidentifier())
print(n3.isprintable())
print(n3.isalnum())
print(n3.isspace())
print(n3.istitle())
print(n3.isdecimal())
print(n3.isascii())
print(n3.isalpha())
print(n3.isnumeric())